### ISSUE TITLE
期中考

### ISSUE THREAD

**Issue by kaochenlong** [kaochenlong/ntub_homework2017#355]
### 請依以下範例格式在底下留言：

1. 學號：(範例) B8306043
2. 完成後的 GitHub 專案網址：(範例) https://github.com/kaochenlong/mybook_store

**Comment by hank40413** [comment]
1. 學號：10346024
2. 完成後的 GitHub 專案網址：https://github.com/hank40413/mybook_store

**Comment by h8254201** [comment]
學號：10346006
完成後的 GitHub 專案網址：https://github.com/h8254201/mybook_store

**Comment by haojunzhang** [comment]
學號：10346016
完成後的 GitHub 專案網址：https://github.com/haojunzhang/mybook_store

**Comment by chenming5050** [comment]
1. 學號：10536002
2. 完成後的 GitHub 專案網址：https://github.com/chenming5050/mybook_store

**Comment by silvia0223y** [comment]
1. 學號：N1036405
2. 完成後的 GitHub 專案網址：https://github.com/silvia0223y/mybook_store

**Comment by ntub10346036** [comment]
1.學號：10346036
2.完成後的 GitHub 專案網址：https://github.com/ntub10346036/homework10346036/tree/master/mybook

**Comment by arthurc0102** [comment]
1. 學號：10256039
2. 完成後的 GitHub 專案網址：https://github.com/arthurc0102/mybook_store

**Comment by 10346013** [comment]
1.學號：10346013
2.完成後的 GitHub 專案網址：https://github.com/10346013/homework0428/tree/master/library13

**Comment by PeggyHsaio** [comment]
1. 學號：10346011
2. 完成後的GitHub專案網址：https://github.com/PeggyHsaio/exam0505

**Comment by wgshtg** [comment]
學號：10536004
完成後的 GitHub 專案網址：https://github.com/wgshtg/library

**Comment by LDarC** [comment]
1.學號：10346031
2.完成後的 GitHub 專案網址：https://github.com/LDarC/midterm-exam

**Comment by jinjiakang** [comment]
1. 學號：10346012
2. 完成後的GitHub專案網址：https://github.com/jinjiakang/midtest

**Comment by a86346480** [comment]
學號：10346007
完成後的 GitHub 專案網址：https://github.com/a86346480/ntub10346007_vote/tree/master/library10346007

**Comment by iamloveez** [comment]
1.學號 : 10346008
2. 完成後的GitHub 專案網址 :https://github.com/iamloveez/10346008/tree/master/10346008

**Comment by a12462004** [comment]
1. 學號：10536011
2. 完成後的 GitHub 專案網址：https://github.com/a12462004/midterm-exam

**Comment by RickyJian** [comment]
1. 學號 : 10346029
2. 完成後的 GitHub 專案網址：https://github.com/RickyJian/mybook_store

**Comment by Shenping** [comment]
1.學號：10346034
2.完成後的GitHub專案網址：https://github.com/Shenping/mybook_store

**Comment by Ann-Lin** [comment]
1.學號 : 10535020
2.完成後的 GitHub 專案網址：https://github.com/Ann-Lin/mybook_store

**Comment by icepineapple** [comment]
學號：10342031
完成後的 GitHub 專案網址：https://github.com/icepineapple/system

**Comment by ccw0727** [comment]
學號：10536006
完成後的 GitHub 專案網址：https://github.com/ccw0727/mybook_store

**Comment by yangyuching** [comment]
學號：10342039
完成後的 GitHub 專案網址：https://github.com/yangyuching/midterm

**Comment by momo200e** [comment]
學號：10536001
完成後的 GitHub 專案網址：https://github.com/momo200e/10536001

**Comment by ntub46010** [comment]
學號：10346010
完成後的 GitHub 專案網址：https://github.com/ntub46010/mybook_store

**Comment by jiangxiang0831** [comment]
學號：10346035
完成後的 GitHub 專案網址：https://github.com/jiangxiang0831/mybook_store

**Comment by zaiyun32** [comment]
學號：10346010
完成後的 GitHub 專案網址：https://github.com/zaiyun32/ruby_mid

**Comment by 10346015** [comment]
學號：10346015
完成後的 GitHub 專案網址：https://github.com/10346015/20170505

**Comment by hihi5404** [comment]
學號：10536017
完成後的 GitHub 專案網址：https://github.com/hihi5404/midterm

**Comment by ccw0727** [comment]
學號：10536006
完成後的 GitHub 專案網址：https://github.com/ccw0727/midterm
