### ISSUE TITLE
期末考

### ISSUE THREAD

**Issue by kaochenlong** [kaochenlong/ntub_homework2017#383]
### 請依以下範例格式在底下留言：

1. 學號：(範例) B8306043
2. 完成後的 GitHub 專案網址：(範例) https://github.com/kaochenlong/mybook_store

**Comment by 10346013** [comment]
1. 10346013
2. 完成後的 GitHub 專案網址：https://github.com/10346013/final

**Comment by ntub10346036** [comment]
1.學號：(範例) 10346036
2.完成後的 GitHub 專案網址：https://github.com/ntub10346036/final10346036

**Comment by ntub10346036** [comment]
1.學號： 10346036
2.完成後的 GitHub 專案網址：https://github.com/ntub10346036/final10346036

**Comment by haojunzhang** [comment]
1.學號： 10346016
2.完成後的 GitHub 專案網址：https://github.com/haojunzhang/student-score-system

**Comment by zaiyun32** [comment]
1.學號： 10346032
2.完成後的 GitHub 專案網址：https://github.com/zaiyun32/ruby_finalexam

**Comment by silvia0223y** [comment]
1.學號： N1036405
2.完成後的 GitHub 專案網址：https://github.com/silvia0223y/Transcripts

**Comment by h8254201** [comment]
1.學號： 10346006
2.完成後的 GitHub 專案網址：https://github.com/h8254201/ruby-final

**Comment by LDarC** [comment]
1.學號： 10346031
2.完成後的 GitHub 專案網址：https://github.com/LDarC/final

**Comment by ntub46010** [comment]
1.學號： 10346010
2.完成後的 GitHub 專案網址：https://github.com/ntub46010/RubyOnRailsTranscript/tree/branch2

**Comment by chenming5050** [comment]
1.學號： 10536002
2.完成後的 GitHub 專案網址：https://github.com/chenming5050/final-exam

**Comment by jiangxiang0831** [comment]
學號：10346035
完成後的 GitHub 專案網址：https://github.com/jiangxiang0831/ruby_final

**Comment by a86346480** [comment]
1.學號：10346007
2.完成後的 GitHub 專案網址：https://github.com/a86346480/ntub10346007_vote/tree/master/finalexam_07

**Comment by PeggyHsaio** [comment]
1. 學號：10346011
2. 完成後的GitHub專案網址：https://github.com/PeggyHsaio/Exam0616.git

**Comment by jinjiakang** [comment]
1. 10346012
2. 完成後的 GitHub 專案網址：https://github.com/jinjiakang/Finaltest2017RUBY.git

**Comment by iamloveez** [comment]
1. 學號 : 10346008
2. 完成後的 GitHub 專案網址：https://github.com/iamloveez/130460080616

**Comment by Shenping** [comment]
1.學號： 10346034
2.完成後的 GitHub 專案網址：https://github.com/Shenping/final

**Comment by 10346015** [comment]
1.學號：10346015
2.完成後的 GitHub 專案網址：https://github.com/10346015/finalexam

**Comment by arthurc0102** [comment]
1. 學號：10256039
2. 完成後的 GitHub 專案網址：<https://github.com/arthurc0102/my-transcripts>

**Comment by hank40413** [comment]
1. 學號：10346024
2. 完成後的 GitHub 專案網址：https://github.com/hank40413/finalExam

**Comment by momo200e** [comment]
學號： 10536001
完成後的 GitHub 專案網址：https://github.com/momo200e/final-exam

**Comment by wgshtg** [comment]
1.學號：10536004
2.完成後的 GitHub 專案網址：https://github.com/wgshtg/score-list

**Comment by a12462004** [comment]
1. 學號：10536011
2. 完成後的 GitHub 專案網址：https://github.com/a12462004/final-exam

**Comment by ccw0727** [comment]
學號：105360006
完成後的 GitHub 專案網址：https://github.com/ccw0727/final-exam

**Comment by hihi5404** [comment]
學號：10536017
完成後的 GitHub 專案網址：https://github.com/hihi5404/final

**Comment by icepineapple** [comment]
學號：10342031
完成後的 GitHub 專案網址：https://github.com/icepineapple/final_exam

**Comment by Ann-Lin** [comment]
學號：10535020
完成後的 GitHub 專案網址：https://rubytt-ztlin62595251865.codeanyapp.com/score_items

**Comment by yangyuching** [comment]
學號：10342039
完成後的 GitHub 專案網址：https://github.com/yangyuching/finalexam
